- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - Aspid
  - Bagel
  - Barratry
  - Cluster
  - CorvaxDelta
  - CorvaxBox
  - CorvaxIshimura
  - CorvaxAvrite
  - Core
  - Fland
  - Kettle
  - Marathon
  - Meta
  - Moose
  - Omega
  - Origin
  - Saltern
  - Packed
