- type: playTimeTracker
  id: JobCentralCommandOperator

- type: playTimeTracker
  id: JobCentralCommandSecGavna

- type: playTimeTracker
  id: JobCentralCommandSecOfficer

- type: playTimeTracker
  id: JobCentralCommandCargo

- type: playTimeTracker
  id: JobCentralCommandAssistant

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobCentralCommandAdmiral

- type: playTimeTracker
  id: JobCentralCommandRCC

- type: playTimeTracker
  id: JobCommanderSalvage

- type: playTimeTracker
  id: JobBlueShield