- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Box
  - Cluster
<<<<<<< HEAD
  - Delta
  #- Train <- return after station anchoring PR is finished and merged
=======
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Train
>>>>>>> c55f443d2584ee9c45d2d1320fb4037a854866a0
