#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    pocket1: BaseMageSpellbook10Spellpoints
  innerClothingSkirt: ClothingUniformJumpskirtColorDarkBlue

- type: startingGear
  id: WizardRedGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    shoes: ClothingShoesWizard
    pocket1: BaseMageSpellbook10Spellpoints
  innerClothingSkirt: ClothingUniformJumpskirtColorRed

- type: startingGear
  id: WizardVioletGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet
    shoes: ClothingShoesWizard
    pocket1: BaseMageSpellbook10Spellpoints
  innerClothingSkirt: ClothingUniformJumpskirtColorPurple

- type: startingGear
  id: WizardHardsuitGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    outerClothing: ClothingOuterHardsuitWizard
    shoes: ClothingShoesWizard
  innerClothingSkirt: ClothingUniformJumpskirtColorPurple
