- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  roles:
  - Borg
  - Boxer
  - Chaplain
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Lox

- type: department
  id: Silicon
  description: department-Osobiy-description
  color: "#EFB341"
  roles:
  - Borg
  - BORGcleaner
  - BORGassist
  - BORGmedical
  - BORGsalvage
  - BORGengineer

- type: department
  id: Cafe
  description: department-Cafe-description
  color: "#F1A51B"
  roles:
  - Bartender
  - Botanist
  - Chefck
  - Chef
  - Zookeeper
  - ServiceWorker

- type: department
  id: Nanotrasen
  description: department-Nanotrasen-description
  color: "#F1A51B"
  roles:
  - ERTsec
  - ERTmedic
  - ERTleader
  - Centralassist
  - CentralOfficial

- type: department
  id: IAA
  description: department-IAA-description
  color: "#EFB341"
  roles:
  - IAA
  - Lawyer

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - Chef
  - IAA # Corvax-IAA
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - SeniorOfficer
  - Detective
  - Warden
  - KTKP
  - Prisoner

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  roles:
  - Boxer
  - Reporter
  - Psychologist
