- type: job
  id: KTKP
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobKTKP
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Maintenance
  - Service
  - Brig
  - External