- type: playTimeTracker
  id: JobChefck

- type: playTimeTracker
  id: JobKTKP

- type: playTimeTracker
  id: JobRab

- type: playTimeTracker
  id: JobRabMaster

- type: playTimeTracker
  id: JobLox

- type: playTimeTracker
  id: JobPirate1lvl

- type: playTimeTracker
  id: JobPirate3lvl

- type: playTimeTracker
  id: JobERTsec

- type: playTimeTracker
  id: JobERTmedic

- type: playTimeTracker
  id: JobERTleader

- type: playTimeTracker
  id: JobCentralOfficial

- type: playTimeTracker
  id: JobCentralassist

- type: playTimeTracker
  id: JobBorgcleaner

- type: playTimeTracker
  id: JobBorgService

- type: playTimeTracker
  id: JobBorgMedical

- type: playTimeTracker
  id: JobBorgMining

- type: playTimeTracker
  id: JobBorgEngineer



